spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoe
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      ddl-auto: none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    post: 587
    username: vuonglinh280202@gmail.com
    password: idvb kgcs wlbp asil
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

